"""Hydrology and rainwater harvesting calculation module.

Implements standard hydrological models (Rational Method / CWC guidelines)
to estimate runoff volume, annual rainwater harvest potential, and
recommended pond storage dimensions.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional
import urllib.request
import json

logger = logging.getLogger(__name__)


@dataclass
class HydrologyResult:
    annual_rainfall_mm: float
    monsoon_rainfall_mm: float
    runoff_coefficient: float
    expected_water_volume_m3: float
    expected_water_volume_liters: float
    expected_water_volume_megaliters: float
    recommended_pond_depth_m: float
    recommended_pond_area_m2: float
    recommended_pond_storage_capacity_m3: float
    recommended_dimensions: str
    estimated_household_days: int
    rainfall_source: str


def fetch_historical_rainfall(lat: float, lon: float, default_rainfall_mm: float = 1150.0) -> tuple[float, str]:
    """Fetch annual rainfall from Open-Meteo historical archive or fallback to regional climate average.
    
    Regional average for Central India (Raipur/Durg, Chhattisgarh) is ~1150-1250 mm.
    """
    try:
        url = (
            f"https://archive-api.open-meteo.com/v1/archive?"
            f"latitude={lat:.4f}&longitude={lon:.4f}&"
            f"start_date=2023-01-01&end_date=2023-12-31&"
            f"daily=precipitation_sum&timezone=auto"
        )
        req = urllib.request.Request(url, headers={"User-Agent": "PondCatchmentPlanner/2.0"})
        with urllib.request.urlopen(req, timeout=2.5) as resp:
            if resp.status == 200:
                data = json.loads(resp.read().decode("utf-8"))
                precip_list = data.get("daily", {}).get("precipitation_sum", [])
                valid_precip = [p for p in precip_list if p is not None]
                if valid_precip and sum(valid_precip) > 100.0:
                    annual_total = float(sum(valid_precip))
                    return round(annual_total, 1), "Open-Meteo Historical Archive (2023)"
    except Exception as exc:
        logger.info(f"Open-Meteo rainfall query skipped ({exc}), using regional climate normal.")
    
    return default_rainfall_mm, "Regional Climatological Normal (IMD 1991-2020)"


def compute_runoff_coefficient(mean_slope_pct: float, soil_type: str = "medium") -> float:
    """Compute runoff coefficient C based on catchment mean slope and soil type.
    
    Based on Indian Central Water Commission (CWC) and USDA-SCS guidelines:
    - Low slope (< 2%): C ~ 0.15 - 0.22
    - Moderate slope (2% - 7%): C ~ 0.25 - 0.35
    - Steep slope (> 7%): C ~ 0.38 - 0.50
    """
    soil_factor = {
        "sandy": -0.05,
        "medium": 0.0,
        "loamy": 0.02,
        "clayey": 0.06,
        "rocky": 0.12,
    }.get(soil_type.lower(), 0.0)

    if mean_slope_pct < 2.0:
        base_c = 0.20
    elif mean_slope_pct <= 7.0:
        # Interpolate between 0.20 and 0.35
        base_c = 0.20 + ((mean_slope_pct - 2.0) / 5.0) * 0.15
    else:
        # Interpolate between 0.35 and 0.48, capping at 0.55
        base_c = min(0.35 + ((mean_slope_pct - 7.0) / 10.0) * 0.13, 0.55)

    c = round(max(0.12, min(0.60, base_c + soil_factor)), 3)
    return c


def calculate_hydrology(
    catchment_area_m2: float,
    mean_slope_pct: float,
    lat: float,
    lon: float,
    override_rainfall_mm: Optional[float] = None,
    soil_type: str = "medium",
    target_pond_depth_m: float = 3.0,
) -> HydrologyResult:
    """Calculate harvestable rainwater volume and recommended pond dimensions.
    
    Formulas:
      V_runoff (m³) = C * (Rainfall_monsoon / 1000) * Catchment_Area_m²
      Recommended Pond Capacity (m³) = V_runoff * Target_Capture_Ratio (0.60)
    """
    if override_rainfall_mm and override_rainfall_mm > 0:
        annual_rainfall = override_rainfall_mm
        rf_source = "User Specified"
    else:
        annual_rainfall, rf_source = fetch_historical_rainfall(lat, lon)

    # In monsoonal climates (India), ~85% of annual rainfall falls during June-Sept
    monsoon_rainfall = round(annual_rainfall * 0.85, 1)

    runoff_c = compute_runoff_coefficient(mean_slope_pct, soil_type)

    # Total runoff volume generated by the catchment during monsoon (m³)
    # V = C * P * A
    rainfall_depth_m = monsoon_rainfall / 1000.0
    runoff_volume_m3 = round(runoff_c * rainfall_depth_m * catchment_area_m2, 1)
    runoff_liters = round(runoff_volume_m3 * 1000.0, 0)
    runoff_megaliters = round(runoff_volume_m3 / 1000.0, 2)

    # Village Pond Sizing:
    # A village pond typically targets storing 50-70% of harvestable runoff
    # to avoid excessive excavation cost while guaranteeing full storage.
    target_capture_ratio = 0.60
    target_storage_m3 = round(runoff_volume_m3 * target_capture_ratio, 1)

    # Standard pond depth: 3.0m (0.5m silt dead storage + 2.0m active + 0.5m freeboard)
    depth_m = max(1.5, min(5.0, target_pond_depth_m))
    
    # Effective water depth for active storage ~ (depth - 0.5m freeboard)
    effective_depth = max(1.0, depth_m - 0.5)

    # Trapezoidal surface area requirement (m²)
    # Using 1.5:1 side slopes: average cross-section factor ~ 0.85
    surface_area_m2 = round(target_storage_m3 / (effective_depth * 0.85), 1)

    # Length to Width ratio of 1.5:1
    # Area = L * W = 1.5 * W²  ==>  W = sqrt(Area / 1.5), L = 1.5 * W
    width_m = round((surface_area_m2 / 1.5) ** 0.5, 1)
    length_m = round(width_m * 1.5, 1)

    dimensions_str = f"{length_m:.1f}m × {width_m:.1f}m × {depth_m:.1f}m (L × W × D)"

    # Socio-economic impact:
    # Standard rural domestic water norm = 55 Litres per capita per day (LPCD)
    # Average family of 5 = 275 L/day.
    # Estimated household-days of water security:
    household_days = int(runoff_liters * 0.70 / 275.0)

    return HydrologyResult(
        annual_rainfall_mm=annual_rainfall,
        monsoon_rainfall_mm=monsoon_rainfall,
        runoff_coefficient=runoff_c,
        expected_water_volume_m3=runoff_volume_m3,
        expected_water_volume_liters=runoff_liters,
        expected_water_volume_megaliters=runoff_megaliters,
        recommended_pond_depth_m=depth_m,
        recommended_pond_area_m2=surface_area_m2,
        recommended_pond_storage_capacity_m3=target_storage_m3,
        recommended_dimensions=dimensions_str,
        estimated_household_days=household_days,
        rainfall_source=rf_source,
    )
